name: CI

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"
env:
    # Define environment variables for OSS configuration
    OSS_BUCKET: test12341241
    OSS_PATH: log
    OSS_REGION: cn-hangzhou
    OSS_ENDPOINT: "${{ secrets.OSS_ENDPOINT }}"
    OSS_ACCESS_KEY_ID: "${{ secrets.OSS_ACCESS_KEY_ID }}"
    OSS_ACCESS_KEY_SECRET: "${{ secrets.OSS_ACCESS_KEY_SECRET }}"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r dev-requirements.txt
      - name: Setup git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
      - name: Test
        run: coverage run -m pytest 
      - name: Lint
        run: make lint
      - name: Update(master)
        if: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: coverage run -a ./scripts/update.py --release
      - name: Update
        if: ${{ !(github.ref == 'refs/heads/master' && github.event_name != 'pull_request') }}
        run: coverage run -a ./scripts/update.py

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ossutil
        run: |
          wget https://gosspublic.alicdn.com/ossutil/1.7.13/ossutil64
          chmod +x ossutil64
          sudo mv ossutil64 /usr/local/bin/ossutil
          
      - name: Test Secrets
        run: |
          echo "OSS_ENDPOINT: ${{ secrets.OSS_ENDPOINT }}"
          echo "OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}"
          echo "OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}"

      - name: Configure ossutil
        run: |
          ossutil config -e "$OSS_ENDPOINT" -i "$OSS_ACCESS_KEY_ID" -k "$OSS_ACCESS_KEY_SECRET" 

      - name: Upload JSON files to OSS
        run: |
          find data/ -name "*.json" -print0 | xargs -0 -I {} ossutil cp {} oss://$OSS_BUCKET/$OSS_PATH/ --acl public-read
        
      # FIXME
      #- name: Report coverage
      #  env:
      #    CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      #  run: |
      #    coverage xml && coverage report
      #    if [[ -n "$CC_TEST_REPORTER_ID" ]]; then\
      #     curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter &&\
      #      chmod +x ./cc-test-reporter &&\
      #      ./cc-test-reporter after-build ;\
      #    fi
