name: Upload JSON Files to OSS

on:
  workflow_call:
    inputs:
      ref:
        description: 'The GitHub ref that triggered the workflow'
        required: true
        type: string
      event_name:
        description: 'The name of the event that triggered the workflow'
        required: true
        type: string
jobs:
  upload_to_oss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ossutil
        run: |
          wget https://gosspublic.alicdn.com/ossutil/1.7.13/ossutil64
          chmod +x ossutil64
          sudo mv ossutil64 /usr/local/bin/ossutil

      - name: Configure ossutil
        run: |
          ossutil config -e ${{ secrets.OSS_ENDPOINT }} -i ${{ secrets.OSS_ACCESS_KEY_ID }} -k ${{ secrets.OSS_ACCESS_KEY_SECRET }} -L  "CN"

      - name: Upload JSON files to OSS
        run: |
          find data/ -name "*.json" -print0 | xargs -0 -I {} ossutil cp {} oss://test12341241/log/ --acl public-read # 替换为你的存储桶名称和 OSS 路径

env:
    # 定义环境，存储桶名称等，这样可以方便修改
    OSS_BUCKET: your-bucket-name
    OSS_PATH: your-oss-path
    OSS_REGION: cn-hangzhou

